name: Cleanup PR Resources
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    # Runner selection based on repository visibility:
    # - Private/internal repositories: sonar-xs
    # - Public repositories: github-ubuntu-latest-s
    {% if cookiecutter.repository_visibility == "public" -%}
    runs-on: github-ubuntu-latest-s
    {% else -%}
    runs-on: sonar-xs
    {% endif -%}
    name: Cleanup
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@v1
