---
name: Release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@07c3b254ac74436e361f4ea8ef70c3e697b9dc48 # 7.6.0
    with:
      version: ${{ '{{' }} inputs.version {{ '}}' }}
